<a href="https://colab.research.google.com/github/sebassanchez5680-tech/Prueba/blob/main/S06_Actividad_01_Calificada_NumPy_271757.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sesión 06 — Actividad calificable: NumPy y preparación de datos

# Actividad calificada — NumPy y preparación de datos

**Programación para Analítica Descriptiva y Predictiva**

Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---


**Nombre completo: Sebastian Miguel Sanchez Salas**  
**Matrícula: 271757**  

---

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa lo visto hasta la Sesión 6: expresiones regulares (`re`), comprensión de listas, `map()`, `lambda`, y NumPy. **No uses pandas ni scikit-learn** — todavía no se han visto en el curso, y su uso no sumará puntos aunque el resultado sea correcto.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso apropiado de las herramientas indicadas en cada enunciado — una solución correcta que ignore la herramienta pedida (por ejemplo, usar un bucle `for` donde se pide `map()` o una operación vectorizada) no obtiene el puntaje completo. Comenta tu código donde el paso no sea evidente.

## Librerías

Ejecuta esta celda antes de empezar.

In [27]:
import re
import numpy as np

## Datos de partida

Una red de 4 estaciones meteorológicas registró temperatura y humedad durante 5 días. Los datos llegaron en un formato de texto crudo, como ocurre frecuentemente al recibir información de sensores o sistemas externos. Ejecuta la siguiente celda para cargar las lecturas — **no la modifiques**.

In [28]:
lecturas_crudas = [
    "EST-01 | Dia1 | Temp: 22.3C | Hum: 60%",
    "EST-01 | Dia2 | Temp: 19.8C | Hum: 64%",
    "EST-01 | Dia3 | Temp: 24.1C | Hum: 58%",
    "EST-01 | Dia4 | Temp: 26.5C | Hum: 55%",
    "EST-01 | Dia5 | Temp: 21.0C | Hum: 63%",
    "EST-02 | Dia1 | Temp: 24.0C | Hum: 70%",
    "EST-02 | Dia2 | Temp: 23.5C | Hum: 72%",
    "EST-02 | Dia3 | Temp: 27.2C | Hum: 65%",
    "EST-02 | Dia4 | Temp: 20.1C | Hum: 74%",
    "EST-02 | Dia5 | Temp: 22.8C | Hum: 69%",
    "EST-03 | Dia1 | Temp: 18.5C | Hum: 80%",
    "EST-03 | Dia2 | Temp: 19.2C | Hum: 78%",
    "EST-03 | Dia3 | Temp: 20.0C | Hum: 77%",
    "EST-03 | Dia4 | Temp: 21.5C | Hum: 75%",
    "EST-03 | Dia5 | Temp: 19.9C | Hum: 79%",
    "EST-04 | Dia1 | Temp: 27.8C | Hum: 50%",
    "EST-04 | Dia2 | Temp: 26.3C | Hum: 52%",
    "EST-04 | Dia3 | Temp: 25.9C | Hum: 53%",
    "EST-04 | Dia4 | Temp: 24.0C | Hum: 56%",
    "EST-04 | Dia5 | Temp: 28.1C | Hum: 49%",
]

print(len(lecturas_crudas), "lecturas cargadas")
print(lecturas_crudas[0])

20 lecturas cargadas
EST-01 | Dia1 | Temp: 22.3C | Hum: 60%


---

## Ejercicio 1 — Extracción con expresiones regulares (10 pts)

Usando `re` y comprensión de listas, extrae de cada cadena en `lecturas_crudas` el identificador de estación (por ejemplo `'EST-01'`) y el valor de temperatura como texto (por ejemplo `'22.3'`, sin la `C`). El resultado debe ser una lista de tuplas `(estacion, temperatura_texto)`, en el mismo orden que `lecturas_crudas`.

*Por qué importa: en la práctica, los datos casi nunca llegan ya estructurados — extraerlos de texto libre es el primer paso de cualquier pipeline de análisis.*

In [29]:
import re

extraidos = [re.findall(r"(EST-\d{2}).*Temp:\s*([\d\.]+)C",l) [0] for l in lecturas_crudas] #usamos findall para encontrar todos lo valores que cumplan con el patron marcado
print(len(extraidos))
print(extraidos[:100])

20
[('EST-01', '22.3'), ('EST-01', '19.8'), ('EST-01', '24.1'), ('EST-01', '26.5'), ('EST-01', '21.0'), ('EST-02', '24.0'), ('EST-02', '23.5'), ('EST-02', '27.2'), ('EST-02', '20.1'), ('EST-02', '22.8'), ('EST-03', '18.5'), ('EST-03', '19.2'), ('EST-03', '20.0'), ('EST-03', '21.5'), ('EST-03', '19.9'), ('EST-04', '27.8'), ('EST-04', '26.3'), ('EST-04', '25.9'), ('EST-04', '24.0'), ('EST-04', '28.1')]


---

## Ejercicio 2 — Construcción del arreglo numérico (10 pts)

A partir de las temperaturas extraídas en el Ejercicio 1 (que están en texto), usa `map()` junto con una conversión a `float` para construir un `ndarray` de tipo numérico. Verifica e imprime su `dtype`.

*Por qué importa: conectar la extracción de texto con un tipo de dato numérico utilizable es un paso que se repite constantemente al preparar datos.*

In [30]:
import numpy as np

temperaturas = [t[1] for t in extraidos] #extraemos solamente las temperaturas de las tuplas del ejercicio 1

# Usamos map para poder aplicar el flotante a cada uno de los elementos de la lista de las temperaturas, ya que se extrajeron como texto
# al usar map deja de ser lista, por lo que utilizamos list para que lo vuelva a ser
#finalmente converitmos todo en un arreglo de numpy
temperatura_nump = np.array(list(map(float, temperaturas)))

print("Arreglo NumPy:",temperatura_nump)
print("El dtype del arreglo es:", temperatura_nump.dtype)

Arreglo NumPy: [22.3 19.8 24.1 26.5 21.  24.  23.5 27.2 20.1 22.8 18.5 19.2 20.  21.5
 19.9 27.8 26.3 25.9 24.  28.1]
El dtype del arreglo es: float64


---

## Ejercicio 3 — Organización en una matriz 2D (10 pts)

Reorganiza el arreglo de temperaturas del Ejercicio 2 en una matriz de 4 filas (una por estación) × 5 columnas (una por día) usando `reshape()`. Los datos ya están ordenados por estación en `lecturas_crudas`, así que no necesitas reordenarlos manualmente. Reporta `shape`, `ndim`, `size` y `dtype` de la matriz resultante.

In [31]:
matriz_temp = temperatura_nump.reshape(4, 5) #usamos reshape para hacer un nuevo array de dos dimensiones apartir del array de 1 dimension hecho en el ejercicio pasado

print("Matriz de temperaturas:\n", matriz_temp)

print("shape:", matriz_temp.shape) # tamaño
print("ndim:", matriz_temp.ndim) # dimension de la matriz
print("size:", matriz_temp.size) #valores
print("dtype:", matriz_temp.dtype) #tipo de datos de la matriz

Matriz de temperaturas:
 [[22.3 19.8 24.1 26.5 21. ]
 [24.  23.5 27.2 20.1 22.8]
 [18.5 19.2 20.  21.5 19.9]
 [27.8 26.3 25.9 24.  28.1]]
shape: (4, 5)
ndim: 2
size: 20
dtype: float64


---

## Ejercicio 4 — Indexado, slicing y transposición (10 pts)

A partir de `matriz_temp`:

1. Extrae la fila completa correspondiente a `EST-03`.
2. Extrae la columna completa correspondiente al Día 4.
3. Extrae la submatriz de las primeras 2 estaciones durante los primeros 3 días.
4. Transpón la matriz con `.T` e imprime su nueva forma (`shape`). En una celda de texto (Markdown) o un comentario, explica en qué situación tendría sentido trabajar con los días como filas y las estaciones como columnas.

In [32]:
est03 = matriz_temp[2, :] #extraemos solamente la fila 3
print("EST-03:", est03)

dia4 = matriz_temp[:, 3] #extraemos solamente la columna dia 4
print("Dia 4:",dia4)

submatriz = matriz_temp[0:2, 0:3] #extraemos la submatriz
print("Submatriz (2x3):\n", submatriz)

matriz_t = matriz_temp.T #nos entrega la transpuesta de la matriz
print("Transpuesta:", matriz_t.shape)

#al tener los dias como filas se puede manejar como series de tiempo cada nuevo dato de tiempo se va guardando en la siguiente linea mientras que las columnas describen a las variables
#como por ejemplo las observaciones de los comportamientos de las acciones a lo largo del tiempo, el nombre de las acciones son las columnas y las filas es el comportamiento de la accion por dia
#de esta manera podemos llevar un registro conforme al tiempo transcurrido


EST-03: [18.5 19.2 20.  21.5 19.9]
Dia 4: [26.5 20.1 21.5 24. ]
Submatriz (2x3):
 [[22.3 19.8 24.1]
 [24.  23.5 27.2]]
Transpuesta: (5, 4)


---

## Ejercicio 5 — Máscaras booleanas, verificación y fancy indexing (15 pts)

1. Usa una máscara booleana sobre `matriz_temp` para identificar qué lecturas superan los 25°C.
2. Usando `any()`, verifica si **alguna** estación tuvo, en algún día, una lectura mayor a 25°C.
3. Usando `all()`, verifica si la estación `EST-04` (fila correspondiente) tuvo **todos** sus días por encima de los 24°C.
4. Usando fancy indexing, reordena las filas de `matriz_temp` según la lista de prioridad `[2, 0, 3, 1]` (es decir, primero EST-03, luego EST-01, EST-04 y EST-02).

*Por qué importa: filtrar por condición, verificar rápidamente supuestos sobre los datos, y reordenar según un criterio externo son operaciones cotidianas al priorizar qué datos revisar primero.*

In [33]:
print(matriz_temp > 25) #mascara booleana para identificar lecturas sobre 25c

print("2. Existe algun dia con temperatura mayor a 25c?: ",(matriz_temp > 25).any()) # Usamos any para saber si hay algun elemento que cumple con la condicion

print("3. Todas las temperaturas de EST-04 son mayor a 24c?: ",(matriz_temp[3, :]  > 24).all()) # Usamos all para saber si todos los elementos cumples la condicion

prioridad = [2, 0, 3, 1]
print("4. Matriz reordenada:\n", matriz_temp[prioridad]) #finalmente usamos fancy indexing para cambiar el orden de las estaciones
#print(matriz_temp)

[[False False False  True False]
 [False False  True False False]
 [False False False False False]
 [ True  True  True False  True]]
2. Existe algun dia con temperatura mayor a 25c?:  True
3. Todas las temperaturas de EST-04 son mayor a 24c?:  False
4. Matriz reordenada:
 [[18.5 19.2 20.  21.5 19.9]
 [22.3 19.8 24.1 26.5 21. ]
 [27.8 26.3 25.9 24.  28.1]
 [24.  23.5 27.2 20.1 22.8]]


---

## Ejercicio 6 — Broadcasting y `np.where()` (15 pts)

Cada estación tiene un descalibre de sensor conocido, dado por este arreglo (en el mismo orden que las filas de `matriz_temp`: EST-01, EST-02, EST-03, EST-04):

```python
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])
```

1. Usa broadcasting para aplicar la corrección correspondiente a cada fila de `matriz_temp` (cada estación se ajusta con su propio valor de `descalibre`). Guarda el resultado en una variable nueva, por ejemplo `matriz_corregida`. **Pista:** si intentas sumar `matriz_temp + descalibre` directamente obtendrás un error de formas incompatibles — el broadcasting solo funciona si `descalibre` tiene la forma `(4, 1)` en lugar de `(4,)`, para que cada valor se alinee con una fila completa. Usa `reshape()` (ya lo conoces del Bloque 2) para darle esa forma antes de sumar.
2. Sobre `matriz_corregida`, usa `np.where()` para generar una matriz paralela de etiquetas de texto: `'alta'` si la lectura corregida supera los 25°C, `'normal'` en caso contrario.

In [34]:
descalibre = np.array([-0.5, 1.2, 0.0, -1.0])

descalibre_columna = descalibre.reshape(4, 1) #usamos reshape para convertir en un vector columna el arreglo proporcionado y no falle a la hora de sumarlo a la matriz

matriz_corregida = matriz_temp + descalibre_columna #ahora si podemos proceder a la suma de cada uno de los valores extra para las columnas
print("1. Matriz corregida:", matriz_corregida)

etiquetas = np.where(matriz_corregida > 25, 'alta', 'normal') # sobre la matriz corregida procedemos a asignar nuevas etiquetas con where para los valores
print("2. Matriz de etiquetas:\n", etiquetas)

1. Matriz corregida: [[21.8 19.3 23.6 26.  20.5]
 [25.2 24.7 28.4 21.3 24. ]
 [18.5 19.2 20.  21.5 19.9]
 [26.8 25.3 24.9 23.  27.1]]
2. Matriz de etiquetas:
 [['normal' 'normal' 'normal' 'alta' 'normal']
 ['alta' 'normal' 'alta' 'normal' 'normal']
 ['normal' 'normal' 'normal' 'normal' 'normal']
 ['alta' 'alta' 'normal' 'normal' 'alta']]


---

## Ejercicio 7 — Agregaciones por eje (15 pts)

Usando `matriz_corregida` del Ejercicio 6:

1. Calcula el promedio y la desviación estándar de temperatura **por estación** (usa el `axis` correspondiente).
2. Calcula el promedio de temperatura **por día** (usa el `axis` correspondiente).
3. Sin usar funciones no vistas en el curso (por ejemplo, sin `argmax`), determina **qué día** tuvo el promedio más alto entre estaciones. Sugerencia: obtén el valor máximo de los promedios por día con `.max()`, y compáralo con el arreglo de promedios por día usando `==` para generar una máscara booleana — la posición con `True` te dice qué día fue.

In [35]:

print("1. Promedio por estacion:", matriz_corregida.mean(axis=1)) #usamos mean para obtener el promedio de las estaciones y axis=1 para usar las columnas
print("   Desviación estándar por estación:", matriz_corregida.std(axis=1))

promedio_dia = matriz_corregida.mean(axis=0)

print("\n2. Promedio por dia:", promedio_dia ) #si usamos axis=0 entonces calculamos por linea en este caso, seria por dia

max_promedio = promedio_dia.max() #usamos max para tener el dia con el promedio mas alto

dia_maximo_mascara = (promedio_dia == max_promedio) #comparamos con el arreglo de los promedios por dia para asignar una mascara booleana

print("\n3. Valor maximo promedio:", max_promedio) #imprimimos el dia con el promedio mas alto
print("   Máscara booleana para encontrar el dia:", dia_maximo_mascara)# mostramos el arreglo

1. Promedio por estacion: [22.24 24.72 19.82 25.42]
   Desviación estándar por estación: [2.36016949 2.27982455 0.99879928 1.4743134 ]

2. Promedio por dia: [23.075 22.125 24.225 22.95  22.875]

3. Valor maximo promedio: 24.225
   Máscara booleana para encontrar el dia: [False False  True False False]


---

## Ejercicio 8 — Síntesis: resumen por estación (15 pts)

Usando `map()` y/o comprensión de listas, genera una lista de cadenas de resumen, una por estación, que combine:

- El identificador de estación extraído en el Ejercicio 1.
- El promedio de temperatura corregida de esa estación (Ejercicio 7), formateado a un decimal.
- Su clasificación predominante (`'alta'` o `'normal'`) — usa `np.unique()` sobre las etiquetas de esa estación (del Ejercicio 6) para encontrar cuál aparece con mayor frecuencia entre las dos.

Formato esperado por cadena: `"EST-01: 23.4°C promedio — clasificación predominante: normal"`

Finalmente, ordena la lista de resúmenes de mayor a menor promedio de temperatura usando `sorted()` con `key` y `lambda` (como en la Sesión 4/5), e imprime el resultado ordenado.

In [36]:
estaciones = ['EST-01', 'EST-02', 'EST-03', 'EST-04']

clasificaciones = []
for fila in etiquetas: # iteramos sobre cada fila (estacion) de la matriz de etiquetas
    valores, conteos = np.unique(fila, return_counts=True) #unique nos ayuda a saber cuantas palabras hay y sus apariciones
    palabra_ganadora = valores[conteos.argmax()] #argmax() nos da el índice del número más alto
    clasificaciones.append(palabra_ganadora)

resumenes = [
    f"{est}: {prom:.1f}°C promedio - clasificación predominante: {clas}"
    for est, prom, clas in zip(estaciones, matriz_corregida.mean(axis=1), clasificaciones)] # lista que usamos praa guardar la cadena de texto con el formato requerido

# ordenamos de mayor a menor promedio con sorted() y lambda
# lambda corta la cadena por espacios texto.split(), toma la segunda palabra
# le quita el 'C' y lo convierte a float para que sepa como ordenar.
# reverse=True hace que vaya de mayor a menor.
resumenes_ordenados = sorted(resumenes, key=lambda texto: float(texto.split()[1].replace('°C', '')), reverse=True)
print(resumenes_ordenados)


['EST-04: 25.4°C promedio - clasificación predominante: alta', 'EST-02: 24.7°C promedio - clasificación predominante: normal', 'EST-01: 22.2°C promedio - clasificación predominante: normal', 'EST-03: 19.8°C promedio - clasificación predominante: normal']


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.
- Revisa que tu nombre y número de control estén en la primera celda.