<a href="https://colab.research.google.com/github/sebassanchez5680-tech/Prueba/blob/main/S06_Actividad_02_ALGEBRALINEAL_271757.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [43]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [44]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [45]:
norma_A = np.linalg.norm(producto_A)#usamos norm para poder conocer las magnitudes de los vectores
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print("Norma A:", norma_A)
print("Norma B:", norma_B)
print("Norma C:", norma_C)

Norma A: 7.449161026585477
Norma B: 6.777167549942971
Norma C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [46]:
dot_AB = producto_A @ producto_B # usamos @ para calcular el producto punto
dot_AC = producto_A @ producto_C

print("producto punto AB",dot_AB)
print("Producto punto AC",dot_AC)

cos_AB = dot_AB / (norma_A * norma_B) #calculamos el coseno del angulo ab
cos_AC = dot_AC / (norma_A * norma_C) #ac

ang_AB = np.degrees(np.arccos(cos_AB)) #obtener el arco coseno, y np.degrees convierte el resultado de radianes a grados.
ang_AC = np.degrees(np.arccos(cos_AC))

print("\nÁngulo entre A y B (grados):", ang_AB)
print("Ángulo entre A y C (grados):", ang_AC)

#El producto B es mas similar a A porque el angulo entre ellos casi es de 2 grados mientras que con c es de 47 grados


producto punto AB 50.46
Producto punto AC 26.5

Ángulo entre A y B (grados): 1.7745815839558179
Ángulo entre A y C (grados): 47.22509268261831


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [47]:
A_uni = producto_A / norma_A
B_uni = producto_B / norma_B
C_uni = producto_C / norma_C

print(" Unitaria A:", np.linalg.norm(A_uni))
print(" Unitaria B:", np.linalg.norm(B_uni))
print(" Unitaria C:", np.linalg.norm(C_uni))

 Unitaria A: 1.0
 Unitaria B: 1.0
 Unitaria C: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [48]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [49]:
print("M * P (Elemento a elemento):\n", M * P)
print("\nM @ P (Multiplicacion matricial):\n", M @ P)
print("\nP @ M :\n", P @ M)

#Los resultados son distintos porque * (elemento a elemento )simplemente multiplica los números que comparten la misma posicion. Por el contrario, @ realiza productos punto entre las filas de la primera matriz y las columnas de la segunda.
#P @ M arroja un resultado diferente a M @ P porque la multiplicación matricial no es conmutativa, como podemos ver los resultados van cambiando de orden.


M * P (Elemento a elemento):
 [[3. 0.]
 [0. 6.]]

M @ P (Multiplicacion matricial):
 [[3.  2. ]
 [1.5 6. ]]

P @ M :
 [[3.  1.5]
 [2.  6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [50]:
det_M = np.linalg.det(M)
M_inv = np.linalg.inv(M)

print("\nDeterminante de M:", det_M)
print("Inversa de M:\n", M_inv)
print("Comprobación (M @ M_inv):\n", np.round(M @ M_inv, 2))



Determinante de M: 5.000000000000001
Inversa de M:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
Comprobación (M @ M_inv):
 [[ 1.  0.]
 [-0.  1.]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [51]:

b = np.array([180, 300])
x = np.linalg.solve(M, b)

print("\nUnidades necesarias (x):", x)
print("Verificacion de M @ x:", M @ x)


Unidades necesarias (x): [48. 84.]
Verificacion de M @ x: [180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [52]:
dist_AB = np.linalg.norm(producto_A - producto_B) # La distancia euclidiana es igual a la norma de la diferencia entre dos vectores
dist_AC = np.linalg.norm(producto_A - producto_C)

print(f"Distancia Euclidiana AB: {dist_AB:.2f}")
print(f"Distancia Euclidiana AC: {dist_AC:.2f}")
print(f"Similitud Coseno AB: {cos_AB:.4f}")#ulizamos los mismos angulos utilizados en el ejercicio 2
print(f"Similitud Coseno AC: {cos_AC:.4f}")

#El producto B es el mas parecido al producto A
# La distancia euclidiana entre A y B es mucho menor (0.71 vs 5.47).
# La similitud coseno entre A y B es mayor y muy cercana a 1 (0.99 vs 0.67).


Distancia Euclidiana AB: 0.71
Distancia Euclidiana AC: 5.47
Similitud Coseno AB: 0.9995
Similitud Coseno AC: 0.6791


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.